---
  .travis.yml:
    hc_secure: "F9sudtYF2VTOuP/Qj+5Aizcq8aJYlUpYWz31tuE+Gj9SrGQaPcKNO4oxe64Ft6gO37Hbg71KNpGRxsQIf0Z8CkUc5fYjhNfBUkoKeAfJB3n2WRmqMXmyu++XY4aSOpbO3cbOQx8/GxVWEhgePm0v17J4osf6ecD3EXBzGTXQc5w="

