name 'evenup-openldap'
version '0.0.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Installs OpenLDAP'
description 'Installs and manages the OpenLDAP service'
project_page 'https://github.com/evenup/evenup-openldap'
dependency 'evenup/rsyslog'
dependency 'evenup/backups'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'ripienaar/concat', '>= 0.2.0'

